version: 2.1

orbs:
  # Always take the latest version of the orb, this allows us to
  # run specs against Solidus supported versions only without the need
  # to change this configuration every time a Solidus version is released
  # or goes EOL.
  solidusio_extensions: solidusio/extensions@volatile

commands:
  setup:
    steps:
      - checkout
      - run:
          name: "Update bundler"
          command: |
            sudo gem update --system
            gem --version
            gem install bundler -v '>=2.3.21' --conservative
            bundle --version

jobs:
  solidus-master:
    executor: solidusio_extensions/sqlite
    steps: ['setup', 'solidusio_extensions/run-tests-solidus-master']
  solidus-current:
    executor: solidusio_extensions/sqlite
    steps: ['setup', 'solidusio_extensions/run-tests-solidus-current']
  solidus-older:
    executor: solidusio_extensions/sqlite
    steps: ['setup', 'solidusio_extensions/run-tests-solidus-older']
  lint-code:
    executor: solidusio_extensions/sqlite
    steps: ['setup', 'solidusio_extensions/lint-code']

workflows:
  "Run specs on supported Solidus versions":
    jobs:
      - solidus-master
      - solidus-current
      - solidus-older
      - lint-code

  "Weekly run specs against master":
    triggers:
      - schedule:
          cron: "0 0 * * 4" # every Thursday
          filters:
            branches:
              only:
                - master
    jobs:
      - solidus-master
      - solidus-current
      - solidus-older
